In [1]:
import respy as rp
import pandas as pd

pd.options.display.max_rows = 999
%load_ext nb_black

In [2]:
model = "kw_97_basic"
_, options, _ = rp.get_example_model(model)
params = pd.read_pickle("params_revised_basic.pkl")

In [3]:
df_options = pd.DataFrame.from_dict(options, orient="index", columns=["value"])

In [4]:
df_options

                                                                  value
estimation_draws                                                    200
estimation_seed                                                     500
estimation_tau                                                      500
interpolation_points                                                 -1
n_periods                                                            50
simulation_agents                                                  5000
simulation_seed                                                     132
solution_draws                                                      500
solution_seed                                                       456
monte_carlo_sequence                                             random
covariates            {'hs_graduate': 'exp_school >= 12', 'co_gradua...

In [5]:
%%javascript
IPython.OutputArea.auto_scroll_threshold = 9999

In [6]:
params

                                                              value  \
category                name
delta                   delta                          7.881765e-01
wage_white_collar       constant                       8.323817e+00
                        exp_school                     9.859541e-02
                        exp_white_collar               1.219786e-01
                        exp_white_collar_square       -1.438115e-01
                        exp_blue_collar                9.994745e-02
                        exp_military                   7.055843e-03
                        type_1                        -6.715314e-02
                        type_2                        -4.248796e-01
                        type_3                        -4.997401e-01
wage_blue_collar        constant                       8.909449e+00
                        exp_school                     1.598533e-02
                        exp_white_collar               6.805592e-02
                        exp_blue_collar                1.576480e-01
                        exp_blue_collar_square        -1.840930e-01
                        exp_military                   8.389442e-02
                        type_1                         2.996736e-01
                        type_2                        -1.029638e-01
                        type_3                         7.083491e-02
wage_military           constant                       8.448384e+00
                        exp_school                     4.479953e-02
                        exp_military                   3.391797e-01
                        exp_military_square           -2.972569e+00
nonpec_school           constant                       4.691647e+04
                        hs_graduate                   -2.985102e+03
                        co_graduate                   -2.640850e+04
                        type_1                        -2.338179e+04
                        type_2                        -3.071378e+04
                        type_3                         2.262546e+02
nonpec_home             constant                       1.649630e+04
                        type_1                         2.232636e+02
                        type_2                        -1.735304e+04
                        type_3                        -9.682662e+03
shocks_sdcorr           sd_blue_collar                 2.291096e-01
                        sd_military                    1.753218e-01
                        sd_white_collar                2.588774e-01
                        sd_school                      1.123812e+02
                        sd_home                        1.955076e+04
                        corr_military_blue_collar     -4.116197e-02
                        corr_white_collar_blue_collar -5.122407e-01
                        corr_white_collar_military    -1.935539e-01
                        corr_school_blue_collar        6.309724e-04
                        corr_school_military           1.657599e-03
                        corr_school_white_collar      -1.591819e-03
                        corr_home_blue_collar         -3.403310e-06
                        corr_home_military             1.562278e-07
                        corr_home_white_collar        -4.809457e-06
                        corr_home_school              -3.072119e-06
meas_error              sd_blue_collar                 3.593076e-01
                        sd_military                    1.432266e-01
                        sd_white_collar                4.062283e-01
type_1                  up_to_nine_years_school        3.510286e-01
                        at_least_ten_years_school     -2.721461e+00
type_2                  up_to_nine_years_school        8.224887e-01
                        at_least_ten_years_school      3.396557e+00
type_3                  up_to_nine_years_school       -8.261054e-01
                        at_least_ten_years_school     -1.807213e-01
initial_exp_school_7    probability                    9.500000e-03
initial_exp_school_8    probability                    4.220000e-02
initial_exp_school_9    probability                    2.018000e-01
initial_exp_school_10   probability                    6.715000e-01
initial_exp_school_11   probability                    7.500000e-02
maximum_exp             school                         2.000000e+01
inadmissibility_penalty inadmissibility_penalty       -4.000000e+05

                                                                                                 comment
category                name
delta                   delta                                                            discount factor
wage_white_collar       constant                       log of rental price if the base skill endowmen...
                        exp_school                     linear return to an additional year of schooli...
                        exp_white_collar                return to experience, same sector, linear (wage)
                        exp_white_collar_square        return to experience, same sector, quadratic (...
                        exp_blue_collar                return to experience, other civilian sector, l...
                        exp_military                   return to experience, military sector, linear ...
                        type_1                                     deviation for type 1 from type 0 in a
                        type_2                                     deviation for type 2 from type 0 in a
                        type_3                                     deviation for type 3 from type 0 in a
wage_blue_collar        constant                       log of rental price if the base skill endowmen...
                        exp_school                     linear return to an additional year of schooli...
                        exp_white_collar               return to experience, other civilian sector, l...
                        exp_blue_collar                 return to experience, same sector, linear (wage)
                        exp_blue_collar_square         return to experience, same sector, quadratic (...
                        exp_military                   return to experience, military sector, linear ...
                        type_1                                     deviation for type 1 from type 0 in b
                        type_2                                     deviation for type 2 from type 0 in b
                        type_3                                     deviation for type 3 from type 0 in b
wage_military           constant                       log of rental price if the base skill endowmen...
                        exp_school                     linear return to an additional year of schooli...
                        exp_military                    return to experience, same sector, linear (wage)
                        exp_military_square            return to experience, same sector, quadratic (...
nonpec_school           constant                       consumption value of school attendance for type 0
                        hs_graduate                                         consumption value of college
                        co_graduate                                 consumption value of graduate school
                        type_1                                   deviation for type 1 from type 0 in edu
                        type_2                                   deviation for type 2 from type 0 in edu
                        type_3                                   deviation for type 3 from type 0 in edu
nonpec_home             constant                         mean value of non-market alternative for type 0
                        type_1                                  deviation for type 1 from type 0 in home
                        type_2                                  deviation for type 2 from type 0 in home
                        type_3                                  deviation for type 3 from type 0 in home
shocks_sdcorr           sd_blue_collar                   standard deviation of the shock in occupation b
                        sd_military                    standard deviation of the shock in occupation ...
                        sd_white_collar                  standard deviation of the shock in occupation a
                        sd_school                      standard deviation of the shock in the educati...
                        sd_home                        standard deviation of the shock in the home se...
                        corr_military_blue_collar       correlation between the shocks in military and b
                        corr_white_collar_blue_collar  correlation between the shocks in occupation a...
                        corr_white_collar_military      correlation between the shocks in military and a
                        corr_school_blue_collar        correlation between the shocks in the educatio...
                        corr_school_military           correlation between the shocks in the educatio...
                        corr_school_white_collar       correlation between the shocks in the educatio...
                        corr_home_blue_collar          correlation between the shocks in home sector ...
                        corr_home_military             correlation between the shocks in home sector ...
                        corr_home_white_collar         correlation between the shocks in home sector ...
                        corr_home_school               correlation between the shocks in home sector ...
meas_error              sd_blue_collar                 SD of the measurement error in wages occupation b
                        sd_military                    SD of the measurement error in wages occupatio...
                        sd_white_collar                SD of the measurement error in wages in occupa...
type_1                  up_to_nine_years_school        effect of up to nine years of schooling on pro...
                        at_least_ten_years_school      effect of at least ten years of schooling on p...
type_2                  up_to_nine_years_school        effect of up to nine years of schooling on pro...
                        at_least_ten_years_school      effect of at least ten years of schooling on p...
type_3                  up_to_nine_years_school        effect of up to nine years of schooling on pro...
                        at_least_ten_years_school      effect of at least ten years of schooling on p...
initial_exp_school_7    probability                    Probability that the initial level of school is 7
initial_exp_school_8    probability                    Probability that the initial level of school is 8
initial_exp_school_9    probability                    Probability that the initial level of school is 9
initial_exp_school_10   probability                    Probability that the initial level of school i...
initial_exp_school_11   probability                    Probability that the initial level of school i...
maximum_exp             school                         Maximum level of experience for school (option...
inadmissibility_penalty inadmissibility_penalty        Penalty to non-pecuniary reward for invalid ch...